//PACKAGE COM.EPAM.AUTOMATION.JAVAIO.OPTIONALTASK.FILE.NEWDIRECTORYPOINT2;
//
//PUBLIC CLASS POINT2JAVAPROGRAM {
//    PRIVATE INT VALUE;
//    PRIVATE DOUBLE RESULT;
//    PRIVATE FLOAT QUALITY;
//
//    PRIVATE VOID METHODONE(FLOAT fl) {
//    }
//
//    PRIVATE VOID METHODTWO(DOUBLE dl) {
//    }
//
//    PRIVATE VOID METHODTHREE() {
//        STRINGBUILDER sb = NEW STRINGBUILDER();
//    }
//
//    PRIVATE VOID METHODFOUR() {
//        STRING[] ARRAY = NEW STRING[]{"zx","xc","qa","xy"};
//    }
//
//    PRIVATE VOID METHODFIVE() {
//        STRING LINE;
//    }
//}
